spring.datasource.url=jdbc:mysql://localhost:3306/firstSpring_db2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=Akb311205?
